services:
  cache:
    image: redis:7.2-alpine
    container_name: sistema_cache
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY:-200mb} --maxmemory-policy ${REDIS_POLICY:-allkeys-lru} # Configura Redis para usar un máximo de memoria y una política de eliminación
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  generador_respuestas:
    build: ./respuestas
    container_name: servicio_respuestas
    volumes:
      - ./dataset:/app/data
      - ./respuestas:/app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - DATASET_PATH=/app/data/buildings.csv
      - FORCE_COLOR=1
    networks:
      - app-network
    depends_on:
      cache:
        condition: service_healthy

  generador_trafico:
    build: ./trafico
    container_name: servicio_trafico
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka:9092 #nuevo para conectar con kafka en vez de redis, es decir, el intermediario entre el generador de tráfico y los consumidores será kafka en vez de redis
      - FORCE_COLOR=1
    volumes:
      - ./trafico:/app
    networks:
      - app-network
    depends_on:
      cache:
        condition: service_healthy
      kafka:
        condition: service_healthy

  metricas:
    build: ./metricas
    container_name: servicio_metricas
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - FORCE_COLOR=1
    ports:
      - "8086:8086"
    networks:
      - app-network
    depends_on:
      cache:
        condition: service_healthy
    volumes:
      - ./resultados:/app/resultados

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  
      KAFKA_CREATE_TOPICS: consultas-principales:3:1,consultas-reintentos:1:1,dlq:1:1 # crea tópicos automáticamente
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build: ./consumidores
    container_name: consumer_principal
    environment:
      - KAFKA_HOST=kafka:9092
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
      cache:
        condition: service_healthy

  consumer_retry: 
    build: ./consumidores
    container_name: consumer_reintento
    environment:
      - KAFKA_HOST=kafka:9092
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - CONSUMER_MODE=retry          # para saber qué tópico leer
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
      cache:
        condition: service_healthy


networks:
  app-network:
    driver: bridge
